//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projector.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations;
    public partial class Person
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Please enter your Last Name")]
        [RegularExpression(@"^.{2,}$", ErrorMessage = "Minimum 2 characters required")]
        [StringLength(50, ErrorMessage = "Maximum 50 characters exceeded")]
        [Display(Name = "Last Name")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Please enter your First Name")]
        [RegularExpression(@"^.{2,}$", ErrorMessage = "Minimum 2 characters required")]
        [StringLength(50, ErrorMessage = "Maximum 50 characters exceeded")]
        [Display(Name = "First Name")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Please enter your User Name in email form")]
        [RegularExpression(@"^.{5,}$", ErrorMessage = "Minimum 5 characters required")]
        [StringLength(200, ErrorMessage = "Maximum  200 characters exceeded")]
        [Display(Name = "User Name")]
        [DataType(DataType.EmailAddress)]
        public string username { get; set; }

        [Required(ErrorMessage = "Please enter your Password")]
        //check this --[RegularExpression(@"^\S+\w{7,11}\S$", ErrorMessage = "Minimum 7 characters required")]
        [StringLength(11, ErrorMessage = "Maximum 11 characters exceeded")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
    
}
